# fly.toml file generated for my-antony-bot on 2023-04-03T12:36:59+03:00

app = "my-antony-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true


